# Generated by Django 3.2 on 2021-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=600, null=True)),
                ('button', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
    ]
