# Generated by Django 3.2 on 2021-04-18 08:47

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='title',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
